apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: brayangonzalezgpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brayangonzalezgpipelinesjavascriptdocker 
    spec:
      containers:
        - name: brayangonzalezgpipelinesjavascriptdocker 
          image: acrbrayang.azurecr.io/brayangonzalezgpipelinesjavascriptdocker
          ports:
          - containerPort: 8080